apiVersion: v1
kind: ReplicationController
metadata:
  name: hellorc
spec:
  replicas: 3
  selector:
    app: helloapp
  template:
    metadata:
      name: helloapp
      labels:
        app: helloapp
    spec:
      containers:
      - name: helloapp
        image: helloapp:v1
        ports:
        - containerPort: 8080
